import {AppProvider} from "@/app/components/AppContext"
import { Roboto } from "next/font/google";
import Header from "./components/layout/Header";
import "./globals.css";

const inter = Roboto({ subsets: ["latin"], weight:['400','500','700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-4xl mx-auto  p-4">
          <AppProvider>
          <Header />
        {children}
        <footer className="border-t p-8 text-center text-gray-500 mt-16">
        &copy; 2024 All rights reserved
      </footer>
        </AppProvider>
        </main>
        </body>
    </html>
  );
}
